title: Lokesh Katuri
emailme: lokesh.katuri26@gmail.com
description: >-
  "My day starts with a good tea."

url: "https://lokesh926.github.io" # Your GitHub Pages URL

theme: minima # Choose a Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
navbar:
  - name: Home
    link: /
  - name: Project
    link: /projects
  - name: Blog
    link: /blogs

# Social media links
social:
  github: lokesh926
  twitter: yourtwitterhandle
  linkedin: https://www.linkedin.com/in/lokesh-katuri/

# Build settings
markdown: kramdown

