theme: minima # Choose a Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
navbar:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: Blog
    link: /blogs

# Social media links
social:
  github: lokesh926
  twitter: yourtwitterhandle
  linkedin: https://www.linkedin.com/in/lokesh-katuri/

# Build settings
markdown: kramdown

