title: Lokesh Katuri
email: lokesh.katuri26@gmail.com
description: >-
  A brief description of your site.
baseurl: "" # Set if your site is in a subdirectory
url: "https://yourusername.github.io" # Your GitHub Pages URL

theme: minima # Choose a Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation links
navbar:
  - name: Home
    link: /
  - name: Project
    link: /about
  - name: Blog
    link: /blog

# Social media links
social:
  github: lokesh926
  twitter: yourtwitterhandle
  linkedin: yourlinkedinprofile

# Build settings
markdown: kramdown

